// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vireon-mobile-menu/PremiumMenu.tsx": () => import("../components/mockups/vireon-mobile-menu/PremiumMenu.tsx")
};
